<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-10-21T21:07:37Z" name="Default suite" finished-at="2022-10-21T21:08:03Z" duration-ms="25842">
    <groups>
    </groups>
    <test started-at="2022-10-21T21:07:37Z" name="Default test" finished-at="2022-10-21T21:08:03Z" duration-ms="25842">
      <class name="com.Automation.testcases.SendMessage">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.Automation.testcases.SendMessage@273444fe]" started-at="2022-10-21T21:07:15Z" name="setUp" finished-at="2022-10-21T21:07:37Z" duration-ms="21724" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="SendMessage()[pri:-1, instance:com.Automation.testcases.SendMessage@273444fe]" started-at="2022-10-21T21:07:37Z" name="SendMessage" finished-at="2022-10-21T21:07:53Z" duration-ms="16333" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SendMessage -->
        <test-method signature="checkSavedMessage()[pri:0, instance:com.Automation.testcases.SendMessage@273444fe]" started-at="2022-10-21T21:07:53Z" name="checkSavedMessage" finished-at="2022-10-21T21:07:54Z" duration-ms="894" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkSavedMessage -->
        <test-method signature="searchMessageInSlack()[pri:1, instance:com.Automation.testcases.SendMessage@273444fe]" started-at="2022-10-21T21:07:54Z" name="searchMessageInSlack" finished-at="2022-10-21T21:08:02Z" duration-ms="7457" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Message to be Saved0.15158192886912514] but found [Message to be Saved0.3424889992771515]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Message to be Saved0.15158192886912514] but found [Message to be Saved0.3424889992771515]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.screens.MessagingPage.searchMessageInSlack(MessagingPage.java:116)
at com.Automation.testcases.SendMessage.searchMessageInSlack(SendMessage.java:48)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- searchMessageInSlack -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.Automation.testcases.SendMessage@273444fe]" started-at="2022-10-21T21:08:02Z" name="tearDown" finished-at="2022-10-21T21:08:03Z" duration-ms="1092" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.Automation.testcases.SendMessage -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
